import React, { useState } from 'react';
import {
  BarChart3,
  TrendingUp,
  Clock,
  DollarSign,
  ShieldCheck,
  CheckCircle2,
  Download,
  Calculator,
} from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from 'recharts';
import { downloadFile } from '../utils/fileGenerators';

export const AnalyticsPage: React.FC = () => {
  const [conversionsPerYear, setConversionsPerYear] = useState<number>(24);

  // ROI calculations
  const manualHoursPerBOM = 360; // ~45 days at 8h/day
  const aiHoursPerBOM = 0.07; // 4.2 min
  const savedHoursPerBOM = manualHoursPerBOM - aiHoursPerBOM;
  const annualHoursSaved = Math.round(savedHoursPerBOM * conversionsPerYear);

  const manualCostPerBOM = 18500;
  const aiCostPerBOM = 3700;
  const savedCostPerBOM = manualCostPerBOM - aiCostPerBOM;
  const annualCostSaved = Math.round(savedCostPerBOM * conversionsPerYear);

  // Chart Data
  const timeChartData = [
    { name: 'Manual Conversion', days: 45, fill: '#DC2626' },
    { name: 'BOMfusionAI', days: 0.003, fill: '#2563EB' },
  ];

  const costChartData = [
    { name: 'Manual Conversion', cost: 18500, fill: '#DC2626' },
    { name: 'BOMfusionAI', cost: 3700, fill: '#16A34A' },
  ];

  const categoryPieData = [
    { name: 'Manufactured', value: 8, color: '#2563EB' },
    { name: 'Purchased', value: 10, color: '#7C3AED' },
    { name: 'Fastener', value: 4, color: '#D97706' },
    { name: 'Consumable', value: 2, color: '#EA580C' },
    { name: 'Floor Stock', value: 1, color: '#64748B' },
  ];

  const handleExportExecutiveReport = () => {
    const reportText = `BOMfusionAI — EXECUTIVE TRANSFORMATION ANALYTICS REPORT
Project: EMA-2024 (Electric Motor Assembly)
Date: ${new Date().toLocaleDateString()}

==================================================
EXECUTIVE SUMMARY
==================================================
Conversion Speed Improvement: 99.8% Reduction (4.2 min vs 45 days)
Direct Cost Savings per Conversion: $14,800 (80% reduction)
AI Mean Confidence Score: 96.4%
Zero-Leakage Rate: 100% (25 of 25 components mapped)

==================================================
ANNUAL ROI PROJECTION (${conversionsPerYear} Conversions/Year)
==================================================
Total Engineering Hours Saved: ${annualHoursSaved.toLocaleString()} hours/year
Total Financial Savings: $${annualCostSaved.toLocaleString()}/year
Platform ROI Multiplier: 14.8x

==================================================
STATION WORKLOAD SUMMARY
==================================================
ST-1: Rotor/Shaft Subassembly — 1,350s (6 Parts)
ST-2: Stator/Frame Subassembly — 900s (5 Parts)
ST-3: Main Core Assembly — 1,260s (5 Parts)
ST-4: End Shields & Fan Cover — 300s (4 Parts)
ST-5: Terminal Box & Final Test — 1,620s (5 Parts)

Report Generated by BOMfusionAI Platform.
`;

    downloadFile(reportText, 'EMA-2024-Executive-Report.txt', 'text/plain');
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Page Heading */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-slate-900 tracking-tight">
            Executive Transformation Analytics
          </h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Performance indicators, cost reductions, conversion speed, and AI confidence metrics
          </p>
        </div>

        <button
          onClick={handleExportExecutiveReport}
          className="bg-blue-600 hover:bg-blue-700 text-white font-medium text-xs px-4 py-2 rounded-md shadow-xs transition-colors flex items-center gap-1.5"
        >
          <Download className="w-4 h-4" />
          Export Executive Report
        </button>
      </div>

      {/* 4 Primary KPI Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-2">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Conversion Speed
            </span>
            <Clock className="w-4 h-4 text-blue-600" />
          </div>
          <p className="text-2xl font-semibold text-blue-600 font-mono">4.2 min</p>
          <p className="text-xs text-emerald-700 font-medium">
            vs 45 Days Manual (99.8% Faster)
          </p>
        </div>

        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-2">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Cost Savings
            </span>
            <DollarSign className="w-4 h-4 text-emerald-600" />
          </div>
          <p className="text-2xl font-semibold text-emerald-600 font-mono">$14,800</p>
          <p className="text-xs text-slate-500">Per Conversion (80% Reduction)</p>
        </div>

        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-2">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-semibold uppercase tracking-wider">
              AI Confidence Score
            </span>
            <TrendingUp className="w-4 h-4 text-purple-600" />
          </div>
          <p className="text-2xl font-semibold text-purple-600 font-mono">96.4%</p>
          <p className="text-xs text-slate-500">Mean Across 25 Components</p>
        </div>

        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-2">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Zero-Leakage Rate
            </span>
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
          </div>
          <p className="text-2xl font-semibold text-emerald-600 font-mono">100%</p>
          <p className="text-xs text-emerald-700 font-medium">25 of 25 Parts Mapped</p>
        </div>
      </div>

      {/* Visualizations Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Chart 1: Time Comparison */}
        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-3">
          <h3 className="text-sm font-semibold text-slate-800">
            Conversion Time: Manual vs BOMfusionAI (Days)
          </h3>
          <div className="h-56 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={timeChartData}>
                <XAxis dataKey="name" stroke="#64748B" fontSize={11} />
                <YAxis unit=" d" stroke="#64748B" fontSize={11} />
                <Tooltip formatter={(val: any) => [`${val} Days`, 'Duration']} />
                <Bar dataKey="days" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 2: Cost Comparison */}
        <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-3">
          <h3 className="text-sm font-semibold text-slate-800">
            Conversion Cost: Manual vs BOMfusionAI ($)
          </h3>
          <div className="h-56 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={costChartData}>
                <XAxis dataKey="name" stroke="#64748B" fontSize={11} />
                <YAxis unit=" $" stroke="#64748B" fontSize={11} />
                <Tooltip formatter={(val: any) => [`$${val}`, 'Cost']} />
                <Bar dataKey="cost" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* ROI Calculator Card */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs space-y-4">
        <div className="flex items-center gap-2">
          <Calculator className="w-5 h-5 text-blue-600" />
          <h3 className="text-sm font-semibold text-slate-800">
            Enterprise Value & ROI Projections Calculator
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-600 mb-1">
              Annual Product BOM Conversions
            </label>
            <input
              type="number"
              value={conversionsPerYear}
              onChange={(e) => setConversionsPerYear(Number(e.target.value) || 1)}
              className="w-full border border-slate-300 rounded px-3 py-2 text-sm text-slate-800 font-mono focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="p-3 bg-blue-50 border border-blue-200 rounded-md">
            <p className="text-xs text-blue-800 font-semibold uppercase">
              Total Annual Hours Saved
            </p>
            <p className="text-2xl font-semibold text-blue-900 mt-1 font-mono">
              {annualHoursSaved.toLocaleString()} <span className="text-xs text-blue-700 font-normal">hrs</span>
            </p>
          </div>

          <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-md">
            <p className="text-xs text-emerald-800 font-semibold uppercase">
              Total Annual Net Savings
            </p>
            <p className="text-2xl font-semibold text-emerald-900 mt-1 font-mono">
              ${annualCostSaved.toLocaleString()}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
